### ISSUE TITLE
Когда выйдет версия для firefox ? 

### ISSUE THREAD

**Issue by un-couteau** [anatolykopyl/vk-mute#12]

**Comment by anatolykopyl** [comment]
Портировал расширение под Firefox. Версия пока скорее всего сырая, но на первый взгляд работает. 
Если все пойдет хорошо, то потом выложу в Firefox Add-ons. 

[Релиз с файлом аддона](https://github.com/anatolykopyl/vk-mute/releases/tag/v1.4)
